name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make setup
      run: make reset
    - name: make test
      run: make test
    - name: make setup
      run: make setup
    - name: make reset
      run: make reset
